apiVersion: v1  # Defines the API version of the service
kind: Service  # Specifies the resource type (Service)
metadata:
  name: mongo-express-service  # Name of the service
spec:
  selector:
    app: mongo-express  # Selector to match the app label for associated pods
  ports:
    - protocol: TCP  # Protocol used for the service (TCP in this case)
      port: 8081  # Port exposed by the service
      targetPort: 8081  # Port on the container that the service will forward traffic to
