apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: User
  name: johncena  # Specify the name of your user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader         # Specify the name of the ClusterRole to bind
  apiGroup: rbac.authorization.k8s.io
