apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups:
  - ""                # Core API group for resources like pods
  resources:
  - secrets            # This clusterrole can only access resource secret
  verbs:            # Actions that can be performed on the resources
  - get
  - list
  - watch
