apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default  # Specify the same namespace as the Role
subjects:
- kind: User  # Can be User, Group, or ServiceAccount
  name: jack  # Name of the user to bind
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader       # Name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io
