apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default  # Specify your desired namespace here
rules:
- apiGroups:
  - ""              # Core API group (for resources like pods)
  resources:
  - pods           # List of resources this role can access
  verbs:          # Actions that can be performed on the resources
  - get
  - list
  - watch
