apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: mysa # this attribute is attaching the service account with our pod
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
